version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 20
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      - npm install -g serverless
      # install composer
      # - curl -sS https://getcomposer.org/installer | php
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      # - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo "Build ${GIT_BRANCH}"
      - php composer.phar install
      - serverless deploy --stage ${GIT_BRANCH}
      # - sam build --use-container --template ${SAM_TEMPLATE}
      # - . ./assume-role.sh ${PIPELINE_EXECUTION_ROLE} feature-deploy
      # - sam deploy --stack-name $(echo ${FEATURE_BRANCH_NAME} | tr -cd '[a-zA-Z0-9-]')
      #               --capabilities CAPABILITY_IAM
      #               --region ${TESTING_REGION}
      #               --s3-bucket ${TESTING_ARTIFACT_BUCKET}
      #               --no-fail-on-empty-changeset
      #               --role-arn ${TESTING_CLOUDFORMATION_EXECUTION_ROLE}
  # migrate after build success
  post_build:
    commands:
      - echo "Run migration ${GIT_BRANCH}"
      - serverless bref:cli --stage=${GIT_BRANCH} -a "migrate --force"
