DependsOn: ServerlessVPCGA
Type: AWS::RDS::DBInstance
Properties:
  MasterUsername: ${self:custom.USERNAME}
  MasterUserPassword: ${self:custom.PASSWORD}
  # authentication type is password and IAM role
  AllocatedStorage: 20
  DBName: ${self:custom.DB_NAME}
  DBInstanceClass: ${self:custom.DB_INSTANCE_CLASS}
  # attach to VPC
  VPCSecurityGroups:
  - !GetAtt ServerlessSecurityGroup.GroupId
  DBSubnetGroupName:
    Ref: ServerlessSubnetGroup
  Engine: postgres
  PubliclyAccessible: false