DependsOn: ServerlessVPC
Type: AWS::EC2::SecurityGroup
Properties:
  GroupDescription: SecurityGroup for Serverless Functions
  VpcId:
    Ref: ServerlessVPC
  SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp: "10.0.0.0/0"
    - IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: "10.0.0.0/0"
  Tags: 
    - 
      Key: "Name"
      Value: "ServerlessSecurityGroup"